apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: iis-ingress
  namespace: default
spec:
  rules:
    - host: dzwin18.northeurope.cloudapp.azure.com
      http:
        paths:
          - backend:
              serviceName: iis
              servicePort: 80
            path: /