{{- if .Values.dependencies.useIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "multicalchart.name" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{ .Values.service.dnsName }}
  rules:
  - host: {{ .Values.service.dnsName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-calc-frontend-svc
          servicePort: 80
{{- end }}