{{- if .Values.dependencies.useAppInsights }}
apiVersion: v1
kind: Secret
metadata:
  name: appinsightsecret
type: Opaque
data:
  appinsightskey: {{ .Values.dependencies.appInsightsSecretValue }}
{{- end }}