apiVersion: "v1"
kind: Pod
metadata:
  name: calc-backend
  labels:
    name: calc-backend
    app: calculator
    language: go
spec:
  containers:
    - name: calc-go-backend
      image: dzkubereg.azurecr.io/calc/go-calc-backend:1001
      ports:
        - containerPort: 80
          name: http         
          protocol: TCP
      env: 
        - name: "INSTRUMENTATIONKEY"
          valueFrom:
            secretKeyRef:
              name: appinsightsecret
              key: appinsightskey
        - name: "PORT"
          value: "80"
  imagePullSecrets:
    - name: kuberegistry