apiVersion: "v1"
kind: Pod
metadata:
  name: calc-backend
  labels:
    name: calc-backend
    app: calculator
spec:
  containers:
    - name: calc-backend
      image: dzkubereg.azurecr.io/calc/js-calc-backend:1001
      ports:
        - containerPort: 3001
          name: http         
          protocol: TCP
      env: 
        - name: "INSTRUMENTATIONKEY"
          valueFrom:
            secretKeyRef:
              name: appinsightsecret
              key: appinsightskey
        - name: "PORT"
          value: "3001"
  imagePullSecrets:
    - name: kuberegistry