apiVersion: v1
kind: ReplicationController
metadata:
  name: calc-frontend
  labels:
    name: calc-frontend
    app: calculator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: calc-frontend
    spec:
        containers:
          - name: calc-frontend
            image: dzregistry.azurecr.io/calc/calc-frontend:latest
            ports:
              - containerPort: 3000
                name: http
                protocol: TCP
            env:       
              - name: "ENDPOINT"
                value: "calc-backend-svc"
              - name: "INSTRUMENTATIONKEY"
                valueFrom:
                  secretKeyRef:
                    name: appinsightsecret
                    key: appinsightskey
              - name: "PORT"
                value: "3000"
        imagePullSecrets:
          - name: kuberegistry 