apiVersion: v1
kind: ReplicationController
metadata:
  name: calc-frontend-rc
  labels:
    name: calc-frontend
    app: calculator
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: calc-frontend
    spec:
        containers:
          - name: calc-frontend
            image: dzkubereg.azurecr.io/calc/js-calc-frontend:1001
            ports:
              - containerPort: 80
                name: http
                protocol: TCP
            env:       
              - name: "ENDPOINT"
                value: "calc-backend-svc"
              - name: "REDIS_HOST"
                valueFrom:
                  secretKeyRef:
                    name: rediscachesecret
                    key: redishostkey
              - name: "REDIS_AUTH"
                valueFrom:
                  secretKeyRef:
                    name: rediscachesecret
                    key: redisauthkey
              - name: "INSTRUMENTATIONKEY"
                valueFrom:
                  secretKeyRef:
                    name: appinsightsecret
                    key: appinsightskey
              - name: "PORT"
                value: "80"
        imagePullSecrets:
          - name: kuberegistry 