apiVersion: v1
kind: Service
metadata:
  name: calc-frontend-svc
  labels:
    name: calc-frontend-svc
    app: calculator
spec:
  selector:
    name: calc-frontend 
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 3000
     protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calc-frontend
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: calc-frontend
        app: calculator
    spec:
      containers:
      - name: calcfrontend
        image: dzregistry.azurecr.io/calc/calc-frontend:latest
        ports:
          - containerPort: 3000
            name: http         
            protocol: TCP
        env: 
          - name: "ENDPOINT"
            value: "calc-backend-svc"
          - name: "INSTRUMENTATIONKEY"
            valueFrom:
              secretKeyRef:
                name: appinsightsecret
                key: appinsightskey
          - name: "PORT"
            value: "3000"
      imagePullSecrets:
      - name: kuberegistry
