apiVersion: v1
kind: ReplicationController
metadata:
  name: calcfrontend
  labels:
    name: calcfrontend
    app: calculator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: calcfrontend
    spec:
        containers:
          - name: calcfrontend
            image: dzregistry.azurecr.io/calc/calc-frontend:latest
            ports:
              - containerPort: 3000
                name: http
                protocol: TCP
            env:       
              - name: "ENDPOINT"
                value: "calcbackendsvc"
              - name: "INSTRUMENTATIONKEY"
                valueFrom:
                  secretKeyRef:
                    name: appinsightsecret
                    key: appinsightskey
              - name: "PORT"
                value: "3000"
        imagePullSecrets:
          - name: kuberegistry 