apiVersion: v1
kind: Pod
metadata:
 name: grafana-mysql
spec:
 containers:
  - image: grafana/grafana
    name: grafana
    ports: 
      - containerPort: 3000
        protocol: TCP
    env:
      - name: "GF_DATABASE_TYPE"
        value: "mysql"
      - name: "GF_DATABASE_HOST"
        value: "dzgrafana.mysql.database.azure.com"
      - name: "GF_DATABASE_USER"
        value: "dzgrafad@dzgrafana"
      - name: "GF_DATABASE_PASSWORD"
        value: "Aj98dFj.1234"
      - name: "GF_DATABASE_db"
        value: "grafana"
      - name: "GF_DATABASE_PORT"
        value: "3306"