apiVersion: "v1"
kind: Pod
metadata:
  name: bluedemo
  labels:
    name: servicedemo
    color: blue
    demo: colorsdemo
spec:
  containers:
    - name: blue
      image: denniszielke/blue:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP 
  # imagePullSecrets:
  #   - name: kuberegistry