apiVersion: "v1"
kind: Pod
metadata:
  name: greendemo
  labels:
    name: servicedemo
    color: green
spec:
  containers:
    - name: blue
      image: hellodemodz234.azurecr.io/blue:latest
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP 
  imagePullSecrets:
    - name: kuberegistry