apiVersion: "v1"
kind: Pod
metadata:
  name: bluedemo
  labels:
    name: blueservicedemo
    color: green
spec:
  containers:
    - name: blue
      image: hellodemodz234.azurecr.io/blue:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP 
  imagePullSecrets:
    - name: kuberegistry