apiVersion: v1
kind: ReplicationController
metadata:
  name: colorsdemo
spec:
  replicas: 5
  selector:
    name: servicedemo
    color: blue
    demo: colorsdemo
  template:
    metadata:
      labels:
        name: servicedemo
        color: blue
        demo: colorsdemo
    spec:
        containers:
        - name: blue
          image: denniszielke/blue:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP 