apiVersion: v1
kind: Service
metadata:
  name: colorservice
  labels:
    name: colorservice
spec:
  selector:
    demo: colorsdemo 
  type: ClusterIP
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
