apiVersion: "v1"
kind: Pod
metadata:
  name: greendemo
  labels:
    name: servicedemo
    color: green
    demo: colorsdemo
spec:
  containers:
    - name: green
      image: dzregistry.azurecr.io/green:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
  imagePullSecrets:
    - name: kuberegistry                 