apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-managed-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default