# Default values for multicalchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
frontendReplicaCount: 2
backendReplicaCount: 3
dependencies:
  useRedis: no
  usePodRedis: no
  redisSecret: rediscachesecret
  useAppInsights: yes
  appInsightsSecretValue: dummyValue
  useIngress: no
image:
  repository: dzkubereg.azurecr.io
  frontendImage: js-calc-frontend
  frontendTag: latest
  backendImage: js-calc-backend
  backendTag: latest
  pullPolicy: Always
  pullSecret: kuberegistry
service:
  frontendType: LoadBalancer
  backendType: ClusterIP
  dnsName: calcName
resources:
  limits:
    cpu: 300m
    memory: 350Mi
  requests:
    cpu: 250m
    memory: 256Mi