# Default values for multicalchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
frontendReplicaCount: 2
backendReplicaCount: 3
dependencies:
  useRedis: false
  usePodRedis: false
  redisSecret: rediscachesecret
  useAppInsights: false
  appInsightsSecretValue: dummyValue
  useIngress: false
image:
  repository: dzkubereg.azurecr.io
  frontendImage: js-calc-frontend
  frontendTag: latest
  backendImage: js-calc-backend
  backendTag: latest
  pullPolicy: Always
service:
  frontendType: LoadBalancer
  backendType: ClusterIP
  dnsName: calcName
resources:
  limits:
    cpu: 150m
    memory: 350Mi
  requests:
    cpu: 100m
    memory: 256Mi