apiVersion: "v1"
kind: Pod
metadata:
  name: js-calc-backend
  labels:
    name: calc-backend
    app: calculator
    language: js
spec:
  containers:
    - name: js-calc-backend
      image: denniszielke/js-calc-backend:latest
      ports:
        - containerPort: 8080
          name: calc-backend        
          protocol: TCP
      env: 
        - name: "PORT"
          value: "8080"